### ISSUE TITLE
Delete the tmp directory after benchmark teardown

### ISSUE THREAD

**Issue by klion26** [dataArtisans/flink-benchmarks#25]
Currently, the statebanchmark did not delete the temp directory after the benchmark teardown, so we'll have many empty directory in `/tmp`,

**Comment by pnowojski** [comment]
Thanks for reporting the issue. 

Since `flink-benchmarks` are now officially a component of Apache Flink project, next time you could use Flink's Apache Jira to fill the issue.

**Comment by pnowojski** [comment]
Issue was resolved by #26

**Comment by klion26** [comment]
thanks for the review and merge, will create Apache Jiar next time~
